### ISSUE TITLE
Error while parsing Subdefinition

### ISSUE THREAD

**Issue by TimShilov** [dderevjanik/wsdl-tsclient-example#1]
This is the first time I'm trying to use this library and I can't get it to work. I have tried to search for existing issues and couldn't find anything related.

The file I use for input is hosted here: https://pastebin.com/mFxaxNTY

Here's what I run and the output I get
```
❯ pnpm wsdl-tsclient --caseInsensitiveNames=true --maxRecursiveDefinitionName=390 --esm --verbose wsdl.wsdl -o ./wsdl
Options
{
  "verbose": true,
  "maxRecursiveDefinitionName": 390,
  "caseInsensitiveNames": true,
  "esm": true
}
Generating soap client from "wsdl.wsdl"
Parsing Service AffiliateService
Parsing Port AffiliateBinding
Parsing Method authenticate
Parsing Definition AuthenticateMessage.AuthenticateMessage
Parsing Definition AuthenticateMessage.locale.locale
Parsing Definition AuthenticateMessage.locale.allowedChildren.allowedChildren
Parsing Definition AuthenticateMessage.locale.allowedChildren.restriction.restriction
Parsing Definition AuthenticateMessage.locale.children.children
Parsing Definition AuthenticateMessage.locale.children.0.0
Parsing Definition AuthenticateMessage.locale.children.0.allowedChildren.allowedChildren
Parsing Definition AuthenticateMessage.locale.children.0.allowedChildren.all.all
Parsing Definition AuthenticateMessage.locale.children.0.allowedChildren.choice.choice
Parsing Definition AuthenticateMessage.locale.children.0.allowedChildren.enumeration.enumeration
Parsing Definition AuthenticateMessage.locale.children.0.allowedChildren.sequence.sequence
Parsing Definition AuthenticateMessage.locale.children.0.allowedChildren.attribute.attribute
Parsing Definition AuthenticateMessage.locale.children.0.allowedChildren.attribute.Symbol.Symbol
Error occured while generating client "wsdl.wsdl"
        Error: Error while parsing Subdefinition for AuthenticateMessage.AuthenticateMessage
1 Errors occured!
```

Digging a bit in the library and adding some more logging I found the main cause which is:
```
TypeError: Cannot use 'in' operator to search for 'undefined' in Symbol($attributes)
    at parseDefinition (/Users/tim.shilov/IdeaProjects/affiliate-etl/node_modules/.pnpm/wsdl-tsclient@1.7.1/node_modules/wsdl-tsclient/dist/src/parser.js:275:25)
    at /Users/tim.shilov/IdeaProjects/affiliate-etl/node_modules/.pnpm/wsdl-tsclient@1.7.1/node_modules/wsdl-tsclient/dist/src/parser.js:397:49
    at Array.forEach (<anonymous>)
    at parseDefinition (/Users/tim.shilov/IdeaProjects/affiliate-etl/node_modules/.pnpm/wsdl-tsclient@1.7.1/node_modules/wsdl-tsclient/dist/src/parser.js:284:38)
    at /Users/tim.shilov/IdeaProjects/affiliate-etl/node_modules/.pnpm/wsdl-tsclient@1.7.1/node_modules/wsdl-tsclient/dist/src/parser.js:397:49
    at Array.forEach (<anonymous>)
    at parseDefinition (/Users/tim.shilov/IdeaProjects/affiliate-etl/node_modules/.pnpm/wsdl-tsclient@1.7.1/node_modules/wsdl-tsclient/dist/src/parser.js:284:38)
    at /Users/tim.shilov/IdeaProjects/affiliate-etl/node_modules/.pnpm/wsdl-tsclient@1.7.1/node_modules/wsdl-tsclient/dist/src/parser.js:397:49
    at Array.forEach (<anonymous>)
    at parseDefinition (/Users/tim.shilov/IdeaProjects/affiliate-etl/node_modules/.pnpm/wsdl-tsclient@1.7.1/node_modules/wsdl-tsclient/dist/src/parser.js:284:38)
```

**Comment by TimShilov** [comment]
Sorry, wrong repo. 🤦‍♂️
